/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Vendas;

import bean.VmanProdutos;
import bean.VmanVendasProdutos;
import dao.ProdutosDAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author user
 */
public class JDlgVendasProdutos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgPedidosProdutos
     */
    JDlgVendas jDlgVendas;
    private boolean incluir;

    public JDlgVendasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTxtQuantidade.setText("1");

        ProdutosDAO produtosDAO = new ProdutosDAO();
        List lista = (List) produtosDAO.listAll();
        for (Object object : lista) {
            jCbxVmanProd.addItem((VmanProdutos) object);
        }

        Util.habilitar(false, jTxtVmanVU, jTxtVmanTotal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCbxVmanProd = new javax.swing.JComboBox<VmanProdutos>();
        jTxtQuantidade = new javax.swing.JTextField();
        jTxtVmanVU = new javax.swing.JTextField();
        jTxtVmanTotal = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jBtnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produtos");

        jCbxVmanProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxVmanProdActionPerformed(evt);
            }
        });

        jTxtQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKeyReleased(evt);
            }
        });

        jTxtVmanVU.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Unitário"));

        jTxtVmanTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-50.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ok-48.png"))); // NOI18N
        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jTxtVmanVU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jTxtVmanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbxVmanProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnOK)
                .addGap(31, 31, 31)
                .addComponent(jBtnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbxVmanProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVmanVU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVmanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnOK))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setTelaAnterior(JDlgVendas jDlgVendas, VmanVendasProdutos vendasProd) {
        this.jDlgVendas = jDlgVendas;
        if (vendasProd != null) {
            incluir = false;
            jCbxVmanProd.setSelectedItem(vendasProd.getVmanProdutos());
            jTxtQuantidade.setText(Util.intToString(vendasProd.getVmanQuantidade()));
        } else {
            incluir = true;
        }
    }
    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        // TODO add your handling code here:
        VmanVendasProdutos vendasProdutos = new VmanVendasProdutos();
        vendasProdutos.setVmanProdutos((VmanProdutos) jCbxVmanProd.getSelectedItem());
        vendasProdutos.setVmanQuantidade(Util.strToInt(jTxtQuantidade.getText()));
        vendasProdutos.setVmanValorUnitario(Util.strToDouble(jTxtVmanVU.getText()));
       
        if (incluir == true) {
            jDlgVendas.controllerVenProd.addBean(vendasProdutos);
        } else {
            jDlgVendas.controllerVenProd.removeBean(jDlgVendas.getjTable1().getSelectedRow());
            jDlgVendas.controllerVenProd.addBean(vendasProdutos);
        }
        setVisible(false);
        
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyReleased
        // TODO add your handling code here:
        if (jTxtQuantidade.getText().isEmpty() == false) {
            VmanProdutos produto = (VmanProdutos) jCbxVmanProd.getSelectedItem();
            int quant = Util.strToInt(jTxtQuantidade.getText());
            jTxtVmanTotal.setText(
                    Util.doubleToString(quant * produto.getVmanPreco())
            );
        } else {
            Util.limpar(jTxtVmanTotal);
        }
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    private void jCbxVmanProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxVmanProdActionPerformed
        // TODO add your handling code here:
        VmanProdutos produto = (VmanProdutos) jCbxVmanProd.getSelectedItem();
        jTxtVmanVU.setText(Util.doubleToString(produto.getVmanPreco()));
        int quant = Util.strToInt(jTxtQuantidade.getText());
        jTxtVmanTotal.setText(
                Util.doubleToString(quant * produto.getVmanPreco())
        );
    }//GEN-LAST:event_jCbxVmanProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProdutos dialog = new JDlgVendasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JComboBox<VmanProdutos> jCbxVmanProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtVmanTotal;
    private javax.swing.JTextField jTxtVmanVU;
    // End of variables declaration//GEN-END:variables
}
