/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Vendas;

import bean.VmanClientes;
import bean.VmanVendas;
import bean.VmanVendasProdutos;
import bean.VmanVendedor;
import dao.ClientesDAO;
import dao.VendasDAO;
import dao.VendasProdutosDAO;
import dao.VendedorAO;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.border.TitledBorder;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author user
 */
public class JDlgVendas extends javax.swing.JDialog {

    VmanControllerVendasProdutoVs controllerVenProd;
    private boolean incluir;

    /**
     * Creates new form JDlgPedidos
     */
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TitledBorder DataNasc = BorderFactory.createTitledBorder("Data da Venda");

        jFmtData.setBorder(DataNasc);
        ClientesDAO clientesDAO = new ClientesDAO();
        List listaC = (List) clientesDAO.listAll();
        for (int i = 0; i < listaC.size(); i++) {
            jCboxCliente.addItem((VmanClientes) listaC.get(i));
        }
        VendedorAO vendedorAO = new VendedorAO();
        List listaV = (List) vendedorAO.listAll();
        for (int i = 0; i < listaV.size(); i++) {
            jCboxVendedor.addItem((VmanVendedor) listaV.get(i));
        }

        controllerVenProd = new VmanControllerVendasProdutoVs();
        controllerVenProd.setList(new ArrayList());
        jTable1.setModel(controllerVenProd);

        Util.habilitar(
                false,
                jBtnAlterar1,
                jBtnExcluirProd,
                jBtnAlterar,
                jBtnExcluir,
                jBtnIncluirProd,
                jBtnConfirmar,
                jBtnCancelar,
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

        try {
            MaskFormatter mascaraDataVenda = new MaskFormatter("##/##/####");
            jFmtData.setFormatterFactory(
                    new DefaultFormatterFactory(mascaraDataVenda)
            );

        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendas.class.getName())
                    .log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo = new javax.swing.JTextField();
        jFmtData = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCboxCliente = new javax.swing.JComboBox<VmanClientes>();
        jTxtTotal = new javax.swing.JTextField();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterar1 = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();
        jCboxVendedor = new javax.swing.JComboBox<VmanVendedor>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 130, 60));
        getContentPane().add(jFmtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 21, 216, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 126, 927, 280));

        jCboxCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        getContentPane().add(jCboxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 220, 60));

        jTxtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        getContentPane().add(jTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 18, 129, 60));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alterar-50.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 426, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-50.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 428, -1, -1));

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-confirmar-50.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 426, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-50.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-50.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 426, -1, -1));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-50.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 426, -1, -1));

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-50.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 151, -1, -1));

        jBtnAlterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-alterar-50.png"))); // NOI18N
        jBtnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 226, -1, -1));

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-50.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 303, 85, -1));

        jCboxVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendedor"));
        jCboxVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboxVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(jCboxVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void total() {
        double total = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            VmanVendasProdutos produto = controllerVenProd.getBean(i);
            total += produto.getVmanQuantidade() * produto.getVmanValorUnitario();
        }

        jTxtTotal.setText("R$ " + String.format("%,.2f", total));
    }

    public VmanVendas viewBean() {
        String valorStr = jTxtTotal.getText()
                .replace("R$", "")
                .replace(".", "")
                .replace(",", ".")
                .trim();

        VmanVendas vendas = new VmanVendas();
        vendas.setVmanIdVendas(Util.strToInt(jTxtCodigo.getText()));
        try {
            vendas.setVmanDataVendas(Util.strToDate(jFmtData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        vendas.setVmanTotal(Util.strToDouble(valorStr));
        vendas.setVmanClientes((VmanClientes) jCboxCliente.getSelectedItem());
        vendas.setVmanVendedor((VmanVendedor) jCboxVendedor.getSelectedItem());

        return vendas;
    }

    public void beanView(VmanVendas vendas) {
        jTxtCodigo.setText(Util.intToString(vendas.getVmanIdVendas()));
        jTxtTotal.setText(Util.doubleToString(vendas.getVmanTotal()));
        jFmtData.setText(Util.dateToStr(vendas.getVmanDataVendas()));
        jCboxCliente.setSelectedItem(vendas.getVmanClientes());
        jCboxVendedor.setSelectedItem(vendas.getVmanVendedor());

        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        List lista = (List) vendasProdutosDAO.listProdutos(vendas);
        controllerVenProd.setList(lista);
    }
    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed

        Util.habilitar(
                true,
                jBtnAlterar1,
                jBtnExcluirProd,
                jBtnIncluirProd,
                jBtnConfirmar,
                jBtnCancelar,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

        Util.habilitar(
                false,
                jBtnIncluir,
                jBtnExcluir,
                jBtnAlterar,
                jBtnPesquisar
        );

        Util.habilitar(false, jTxtCodigo);
        jFmtData.grabFocus();

        incluir = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed
    public JTable getjTable1() {
        return jTable1;
    }
    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (Util.perguntar("Deseja excluir ?")) {
            VendasDAO vendasDAO = new VendasDAO();
            VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                VmanVendasProdutos vp = controllerVenProd.getBean(i);
                vendasProdutosDAO.delete(vp);
            }

            vendasDAO.delete(viewBean());
        }

        Util.limpar(
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jCboxVendedor,
                jTxtTotal
        );

        Util.habilitar(false, jBtnConfirmar, jBtnCancelar, jBtnAlterar, jBtnExcluir);
        Util.habilitar(true, jTxtCodigo, jFmtData, jTxtTotal, jCboxCliente, jCboxVendedor, jBtnIncluir, jBtnPesquisar);

        controllerVenProd.setList(new ArrayList<>());
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        VendasDAO vendasDAO = new VendasDAO();
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        VmanVendas vendas = viewBean();

        if (incluir) {
            vendasDAO.insert(vendas);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                VmanVendasProdutos vp = controllerVenProd.getBean(i);
                vp.setVmanVendas(vendas);
                vendasProdutosDAO.insert(vp);
            }
        } else {
            vendasDAO.update(vendas);
            vendasProdutosDAO.deleteProdutos(vendas);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                VmanVendasProdutos vp = controllerVenProd.getBean(i);
                vp.setVmanVendas(vendas);
                vendasProdutosDAO.insert(vp);
            }
        }

        Util.habilitar(false,
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jCboxVendedor,
                jTxtTotal,
                jBtnConfirmar,
                jBtnCancelar
        );

        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);

        Util.limpar(
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jCboxVendedor,
                jTxtTotal
        );

        controllerVenProd.setList(new ArrayList<>());
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(
                false,
                jBtnAlterar1,
                jBtnExcluirProd,
                jBtnIncluirProd,
                jBtnConfirmar,
                jBtnCancelar,
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

        Util.habilitar(
                true,
                jBtnIncluir,
                jBtnExcluir,
                jBtnAlterar,
                jBtnPesquisar
        );

        Util.limpar(
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgVendasPesquisar jDlgVendasPesquisar = new JDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaAnterior(this);
        jDlgVendasPesquisar.setVisible(true);
        Util.habilitar(true, jBtnAlterar, jBtnExcluir);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(
                true,
                jBtnAlterar1, // alterar produto
                jBtnExcluirProd,
                jBtnIncluirProd,
                jBtnConfirmar,
                jBtnCancelar,
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

        Util.limpar(
                jTxtCodigo,
                jFmtData,
                jCboxCliente,
                jTxtTotal,
                jCboxVendedor
        );

        Util.habilitar(
                false,
                jBtnIncluir,
                jBtnExcluir,
                jBtnAlterar,
                jBtnPesquisar,
                jTxtTotal
        );
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jFmtData.setText(hoje.format(fmt));
        jTxtCodigo.grabFocus();
        incluir = true;
        controllerVenProd.setList(new ArrayList());
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgVendasProdutos dlg = new JDlgVendasProdutos(null, true);
        dlg.setTelaAnterior(this, null);
        dlg.setVisible(true);
        total();
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar1ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Selecione uma linha!");
            return;
        }

        VmanVendasProdutos vp = controllerVenProd.getBean(jTable1.getSelectedRow());
        JDlgVendasProdutos dlg = new JDlgVendasProdutos(null, true);
        dlg.setTelaAnterior(this, vp);
        dlg.setVisible(true);
        total();
    }//GEN-LAST:event_jBtnAlterar1ActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Selecione uma linha!");
            return;
        }

        if (Util.perguntar("Deseja excluir o produto ?")) {
            controllerVenProd.removeBean(jTable1.getSelectedRow());
            total();
        }
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    private void jCboxVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboxVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboxVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterar1;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<VmanClientes> jCboxCliente;
    private javax.swing.JComboBox<VmanVendedor> jCboxVendedor;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables


}
