/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Clientes.JDlgClientes;
import view.Usuarios.JDlgUsuarios;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import view.Produtos.JDlgProdutos;
import view.Vendas.JDlgVendas;

/**
 *
 * @author user
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setExtendedState(JFrmPrincipal.MAXIMIZED_BOTH);
        ImageIcon claro = new ImageIcon("src/img/wallpaper.jpg");
        ImageIcon dark = new ImageIcon("src/img/dark.jpg");
        ImageIcon padrao = new ImageIcon("src/img/padrao.jpg");
        Image claroImg = dark.getImage();
        Image darkImg = dark.getImage();
        Image padraoImg = padrao.getImage();

        JPanel background = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(darkImg, 0, 0, getWidth(), getHeight(), this);
            }
        };

        setContentPane(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMnTemaclaro = new javax.swing.JMenuItem();
        jMnTemaEscuro = new javax.swing.JMenuItem();
        jMnTemaPadrao = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cadastro-40.png"))); // NOI18N
        jMenu2.setText("Cadastro");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-administrador-40.png"))); // NOI18N
        jMenuItem6.setText("Usuários");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salário-masculino-40.png"))); // NOI18N
        jMenuItem7.setText("Vendedor");
        jMenu2.add(jMenuItem7);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-homem-homem-40.png"))); // NOI18N
        jMenuItem11.setText("Cliente");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chocolate-40.png"))); // NOI18N
        jMenuItem10.setText("Produtos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fechar-janela-40.png"))); // NOI18N
        jMenuItem9.setText("Sair");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-banco-de-dados-40.png"))); // NOI18N
        jMenu3.setText("Movimento");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-balcão-de-caixa-40.png"))); // NOI18N
        jMenuItem1.setText("Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-theme-40.png"))); // NOI18N
        jMenu4.setText("Tema");

        jMnTemaclaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-droid-40.png"))); // NOI18N
        jMnTemaclaro.setText("Claro");
        jMnTemaclaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaclaroActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaclaro);

        jMnTemaEscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dark-49.png"))); // NOI18N
        jMnTemaEscuro.setText("Escuro");
        jMnTemaEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaEscuroActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaEscuro);

        jMnTemaPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-blond-40.png"))); // NOI18N
        jMnTemaPadrao.setText("Padrão");
        jMnTemaPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaPadraoActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaPadrao);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);            // exibe
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(this, true);
        jDlgClientes.setLocationRelativeTo(this); // centraliza
        jDlgClientes.setVisible(true);            // exibe


    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMnTemaclaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaclaroActionPerformed
        // TODO add your handling code here:
        try {
            ImageIcon claro = new ImageIcon("src/img/wallpaper.jpg");
            Image claroImg = claro.getImage();
            JPanel background = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(claroImg, 0, 0, getWidth(), getHeight(), this);
                }
            };

            setContentPane(background);
            UIManager.setLookAndFeel(new FlatLightLaf());

            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMnTemaclaroActionPerformed

    private void jMnTemaEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaEscuroActionPerformed
        // TODO add your handling code here:
        try {
            ImageIcon dark = new ImageIcon("src/img/dark.jpg");
            Image darkImg = dark.getImage();
            JPanel background = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(darkImg, 0, 0, getWidth(), getHeight(), this);
                }
            };

            setContentPane(background);
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMnTemaEscuroActionPerformed

    private void jMnTemaPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaPadraoActionPerformed
        // TODO add your handling code here:
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            SwingUtilities.updateComponentTreeUI(this);
            ImageIcon padrao = new ImageIcon("src/img/padrao.jpg");
            Image padraoImg = padrao.getImage();
            JPanel background = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(padraoImg, 0, 0, getWidth(), getHeight(), this);
                }
            };
            setContentPane(background);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jMnTemaPadraoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgUsuarios = new JDlgProdutos(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDlgVendas jDlgUsuarios = new JDlgVendas(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMnTemaEscuro;
    private javax.swing.JMenuItem jMnTemaPadrao;
    private javax.swing.JMenuItem jMnTemaclaro;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
