/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PrincipalELogin;

import view.Clientes.JDlgClientes;
import view.Usuarios.JDlgUsuarios;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import view.Clientes.JDlgConsultaClientes;
import view.Produtos.JDlgProdutos;
import view.Vendas.JDlgVendas;

/**
 *
 * @author user
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    ImageIcon claro = new ImageIcon("src/img/wallpaper.jpg");
    ImageIcon dark = new ImageIcon("src/img/dark.jpg");
    ImageIcon padrao = new ImageIcon("src/img/padrao.jpg");
    Image claroImg = dark.getImage();
    Image darkImg = dark.getImage();
    Image padraoImg = padrao.getImage();

    JPanel background = new JPanel() {  
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(darkImg, 0, 0, getWidth(), getHeight(), this);
        }
    };

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setExtendedState(JFrmPrincipal.MAXIMIZED_BOTH);
        
        getContentPane().add(background, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnClientes = new javax.swing.JButton();
        jBtnVendedor = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBntConsultaClientes = new javax.swing.JButton();
        jBntConsultaVendas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMnUser = new javax.swing.JMenuItem();
        jMnVendedor = new javax.swing.JMenuItem();
        jMnClientes = new javax.swing.JMenuItem();
        jMnProd = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMbnVendas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMnConsultaCliente = new javax.swing.JMenuItem();
        jMnConsultaVendedor = new javax.swing.JMenuItem();
        jMnConsultasProdutos = new javax.swing.JMenuItem();
        jMnConsultasVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMnTemaclaro = new javax.swing.JMenuItem();
        jMnTemaEscuro = new javax.swing.JMenuItem();
        jMnTemaPadrao = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem8.setText("jMenuItem8");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-homem-homem-40.png"))); // NOI18N
        jBtnClientes.setFocusable(false);
        jBtnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientes);

        jBtnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-administrador-40.png"))); // NOI18N
        jBtnVendedor.setFocusable(false);
        jBtnVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendedor);

        jBtnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-balcão-de-caixa-40.png"))); // NOI18N
        jBtnVendas.setFocusable(false);
        jBtnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendas);
        jToolBar1.add(jSeparator1);

        jBntConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-homem-homem-40.png"))); // NOI18N
        jBntConsultaClientes.setFocusable(false);
        jBntConsultaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntConsultaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntConsultaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntConsultaClientes);

        jBntConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-balcão-de-caixa-40.png"))); // NOI18N
        jBntConsultaVendas.setFocusable(false);
        jBntConsultaVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntConsultaVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntConsultaVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntConsultaVendas);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cadastro-40.png"))); // NOI18N
        jMenu2.setText("Cadastro");

        jMnUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-administrador-40.png"))); // NOI18N
        jMnUser.setText("Usuários");
        jMnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUserActionPerformed(evt);
            }
        });
        jMenu2.add(jMnUser);

        jMnVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salário-masculino-40.png"))); // NOI18N
        jMnVendedor.setText("Vendedor");
        jMnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMnVendedor);

        jMnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-homem-homem-40.png"))); // NOI18N
        jMnClientes.setText("Cliente");
        jMnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMnClientes);

        jMnProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chocolate-40.png"))); // NOI18N
        jMnProd.setText("Produtos");
        jMnProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnProdActionPerformed(evt);
            }
        });
        jMenu2.add(jMnProd);
        jMenu2.add(jSeparator3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-fechar-janela-40.png"))); // NOI18N
        jMenuItem9.setText("Sair");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-banco-de-dados-40.png"))); // NOI18N
        jMenu3.setText("Movimento");

        jMbnVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMbnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-balcão-de-caixa-40.png"))); // NOI18N
        jMbnVendas.setText("Vendas");
        jMbnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMbnVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jMbnVendas);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-50.png"))); // NOI18N
        jMenu5.setText("Consulta");

        jMnConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-grupo-de-usuário-homem-homem-40.png"))); // NOI18N
        jMnConsultaCliente.setText("Clientes");
        jMnConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConsultaClienteActionPerformed(evt);
            }
        });
        jMenu5.add(jMnConsultaCliente);

        jMnConsultaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salário-masculino-40.png"))); // NOI18N
        jMnConsultaVendedor.setText(" Vendedor");
        jMnConsultaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConsultaVendedorActionPerformed(evt);
            }
        });
        jMenu5.add(jMnConsultaVendedor);

        jMnConsultasProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chocolate-40.png"))); // NOI18N
        jMnConsultasProdutos.setText("Produtos");
        jMnConsultasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConsultasProdutosActionPerformed(evt);
            }
        });
        jMenu5.add(jMnConsultasProdutos);

        jMnConsultasVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-balcão-de-caixa-40.png"))); // NOI18N
        jMnConsultasVendas.setText("Vendas");
        jMnConsultasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnConsultasVendasActionPerformed(evt);
            }
        });
        jMenu5.add(jMnConsultasVendas);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-theme-40.png"))); // NOI18N
        jMenu4.setText("Tema");

        jMnTemaclaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-droid-40.png"))); // NOI18N
        jMnTemaclaro.setText("Claro");
        jMnTemaclaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaclaroActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaclaro);

        jMnTemaEscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dark-49.png"))); // NOI18N
        jMnTemaEscuro.setText("Escuro");
        jMnTemaEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaEscuroActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaEscuro);

        jMnTemaPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-blond-40.png"))); // NOI18N
        jMnTemaPadrao.setText("Padrão");
        jMnTemaPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnTemaPadraoActionPerformed(evt);
            }
        });
        jMenu4.add(jMnTemaPadrao);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUserActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);            // exibe
    }//GEN-LAST:event_jMnUserActionPerformed

    private void jMnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClientesActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(this, true);
        jDlgClientes.setLocationRelativeTo(this); // centraliza
        jDlgClientes.setVisible(true);            // exibe


    }//GEN-LAST:event_jMnClientesActionPerformed

    private void jMnTemaclaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaclaroActionPerformed
        // TODO add your handling code here:
        try {

            
            getContentPane().removeAll();
            background = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(claroImg, 0, 0, getWidth(), getHeight(), this);
                }
            };

            getContentPane().add(background, BorderLayout.CENTER);
            UIManager.setLookAndFeel(new FlatLightLaf());

            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMnTemaclaroActionPerformed

    private void jMnTemaEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaEscuroActionPerformed
        // TODO add your handling code here:
        try {
            
            getContentPane().removeAll();
            background = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(darkImg, 0, 0, getWidth(), getHeight(), this);
                }
            };

            getContentPane().add(background, BorderLayout.CENTER);
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMnTemaEscuroActionPerformed

    private void jMnTemaPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnTemaPadraoActionPerformed
        // TODO add your handling code here:
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            SwingUtilities.updateComponentTreeUI(this);
            
            getContentPane().removeAll();
            
            JPanel background2 = new JPanel() {
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(padraoImg, 0, 0, getWidth(), getHeight(), this);
                }
            };
            getContentPane().add(background2, BorderLayout.CENTER);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jMnTemaPadraoActionPerformed

    private void jMnProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnProdActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgUsuarios = new JDlgProdutos(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnProdActionPerformed

    private void jMbnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMbnVendasActionPerformed
        // TODO add your handling code here:
        JDlgVendas jDlgUsuarios = new JDlgVendas(this, true);
        jDlgUsuarios.setLocationRelativeTo(this); // centraliza
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMbnVendasActionPerformed

    private void jMnConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsultaClienteActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClientes conclki = new JDlgConsultaClientes(this, true);
        conclki.setLocationRelativeTo(this); // centraliza
        conclki.setVisible(true);
    }//GEN-LAST:event_jMnConsultaClienteActionPerformed

    private void jMnConsultaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsultaVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsultaVendedorActionPerformed

    private void jMnConsultasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsultasProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsultasProdutosActionPerformed

    private void jMnConsultasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnConsultasVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnConsultasVendasActionPerformed

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        // TODO add your handling code here:
        jMnClientesActionPerformed(null);
    }//GEN-LAST:event_jBtnClientesActionPerformed

    private void jBtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorActionPerformed
        // TODO add your handling code here:
        jMnVendedorActionPerformed(null);
    }//GEN-LAST:event_jBtnVendedorActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasActionPerformed
        // TODO add your handling code here:
        jMbnVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jBntConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntConsultaClientesActionPerformed
        // TODO add your handling code here:
        jMnConsultaClienteActionPerformed(null);
    }//GEN-LAST:event_jBntConsultaClientesActionPerformed

    private void jBntConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntConsultaVendasActionPerformed
        // TODO add your handling code here:
        jMnConsultasVendasActionPerformed(null);
    }//GEN-LAST:event_jBntConsultaVendasActionPerformed

    private void jMnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntConsultaClientes;
    private javax.swing.JButton jBntConsultaVendas;
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JButton jBtnVendedor;
    private javax.swing.JMenuItem jMbnVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMnClientes;
    private javax.swing.JMenuItem jMnConsultaCliente;
    private javax.swing.JMenuItem jMnConsultaVendedor;
    private javax.swing.JMenuItem jMnConsultasProdutos;
    private javax.swing.JMenuItem jMnConsultasVendas;
    private javax.swing.JMenuItem jMnProd;
    private javax.swing.JMenuItem jMnTemaEscuro;
    private javax.swing.JMenuItem jMnTemaPadrao;
    private javax.swing.JMenuItem jMnTemaclaro;
    private javax.swing.JMenuItem jMnUser;
    private javax.swing.JMenuItem jMnVendedor;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
