package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VmanVendasProdutos generated by hbm2java
 */
@Entity
@Table(name = "vman_vendas_produtos",
         catalog = "db_vinicius_nunes"
)
public class VmanVendasProdutos implements java.io.Serializable {

    private int vmanIdVendasProdutos;
    private VmanProdutos vmanProdutos;
    private VmanVendas vmanVendas;
    private int vmanQuantidade;
    private double vmanValorUnitario;

    public VmanVendasProdutos() {
    }

    public VmanVendasProdutos(int vmanIdVendasProdutos) {
        this.vmanIdVendasProdutos = vmanIdVendasProdutos;
    }

    public VmanVendasProdutos(int vmanIdVendasProdutos, VmanProdutos vmanProdutos, VmanVendas vmanVendas, int vmanQuantidade, double vmanValorUnitario) {
        this.vmanIdVendasProdutos = vmanIdVendasProdutos;
        this.vmanProdutos = vmanProdutos;
        this.vmanVendas = vmanVendas;
        this.vmanQuantidade = vmanQuantidade;
        this.vmanValorUnitario = vmanValorUnitario;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "vman_idVendas_produtos", unique = true, nullable = false)
    public int getVmanIdVendasProdutos() {
        return this.vmanIdVendasProdutos;
    }

    public void setVmanIdVendasProdutos(int vmanIdVendasProdutos) {
        this.vmanIdVendasProdutos = vmanIdVendasProdutos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vman_produtos")
    public VmanProdutos getVmanProdutos() {
        return this.vmanProdutos;
    }

    public void setVmanProdutos(VmanProdutos vmanProdutos) {
        this.vmanProdutos = vmanProdutos;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vman_vendas")
    public VmanVendas getVmanVendas() {
        return this.vmanVendas;
    }

    public void setVmanVendas(VmanVendas vmanVendas) {
        this.vmanVendas = vmanVendas;
    }

    @Column(name = "vman_quantidade")
    public int getVmanQuantidade() {
        return this.vmanQuantidade;
    }

    public void setVmanQuantidade(int vmanQuantidade) {
        this.vmanQuantidade = vmanQuantidade;
    }

    @Column(name = "vman_valor_unitario", precision = 10)
    public double getVmanValorUnitario() {
        return this.vmanValorUnitario;
    }

    public void setVmanValorUnitario(double vmanValorUnitario) {
        this.vmanValorUnitario = vmanValorUnitario;
    }

}
