package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VmanProdutos generated by hbm2java
 */
@Entity
@Table(name="vman_produtos"
    ,catalog="db_vinicius_nunes"
)
public class VmanProdutos  implements java.io.Serializable {


     private int vmanIdProdutos;
     private String vmanProduto;
     private String vmanDescricao;
     private double vmanPreco;
     private int vmanQuantidade;
     private int vmanPorcentagemCacau;
     private int vmanGramas;
     private String vmanAtivo;
  
    public VmanProdutos() {
    }

	
    public VmanProdutos(int vmanIdProdutos) {
        this.vmanIdProdutos = vmanIdProdutos;
    }
    public VmanProdutos(int vmanIdProdutos, String vmanProduto, String vmanDescricao, double vmanPreco, int vmanQuantidade, int vmanPorcentagemCacau, int vmanGramas, String vmanAtivo) {
       this.vmanIdProdutos = vmanIdProdutos;
       this.vmanProduto = vmanProduto;
       this.vmanDescricao = vmanDescricao;
       this.vmanPreco = vmanPreco;
       this.vmanQuantidade = vmanQuantidade;
       this.vmanPorcentagemCacau = vmanPorcentagemCacau;
       this.vmanGramas = vmanGramas;
       this.vmanAtivo = vmanAtivo;
     
    }
   
     @Id 

    
    @Column(name="vman_idProdutos", unique=true, nullable=false)
    public int getVmanIdProdutos() {
        return this.vmanIdProdutos;
    }
    
    public void setVmanIdProdutos(int vmanIdProdutos) {
        this.vmanIdProdutos = vmanIdProdutos;
    }

    
    @Column(name="vman_produto", length=100)
    public String getVmanProduto() {
        return this.vmanProduto;
    }
    
    public void setVmanProduto(String vmanProduto) {
        this.vmanProduto = vmanProduto;
    }

    
    @Column(name="vman_descricao")
    public String getVmanDescricao() {
        return this.vmanDescricao;
    }
    
    public void setVmanDescricao(String vmanDescricao) {
        this.vmanDescricao = vmanDescricao;
    }

    
    @Column(name="vman_preco", precision=10)
    public double getVmanPreco() {
        return this.vmanPreco;
    }
    
    public void setVmanPreco(double vmanPreco) {
        this.vmanPreco = vmanPreco;
    }

    
    @Column(name="vman_quantidade")
    public int getVmanQuantidade() {
        return this.vmanQuantidade;
    }
    
    public void setVmanQuantidade(int vmanQuantidade) {
        this.vmanQuantidade = vmanQuantidade;
    }

    
    @Column(name="vman_porcentagemCacau")
    public int getVmanPorcentagemCacau() {
        return this.vmanPorcentagemCacau;
    }
    
    public void setVmanPorcentagemCacau(int vmanPorcentagemCacau) {
        this.vmanPorcentagemCacau = vmanPorcentagemCacau;
    }

    
    @Column(name="vman_gramas")
    public int getVmanGramas() {
        return this.vmanGramas;
    }
    
    public void setVmanGramas(int vmanGramas) {
        this.vmanGramas = vmanGramas;
    }

    
    @Column(name="vman_ativo", length=1)
    public String getVmanAtivo() {
        return this.vmanAtivo;
    }
    
    public void setVmanAtivo(String vmanAtivo) {
        this.vmanAtivo = vmanAtivo;
    }


   @Override
    public String toString() {
        return this.vmanIdProdutos + " - " + this.vmanProduto;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof VmanClientes) {
            VmanProdutos vmanProduto = (VmanProdutos) object;
            if (vmanProduto.getVmanIdProdutos()== this.getVmanIdProdutos()) {
                return true;
            }
        }
        return false;
    }


}


