package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmanClientes generated by hbm2java
 */
@Entity
@Table(name="vman_clientes"
    ,catalog="db_vinicius_nunes"
)
public class VmanClientes  implements java.io.Serializable {


     private int vmanIdClientes;
     private String vmanNome;
     private String vmanCpf;
     private String vmanRg;
     private String vmanSexo;
     private Date vmanDataNascimento;
     private String vmanEmail;
     private String vmanCep;
     private String vmanendereço;
     private String vmanBairro;
     private String vmanCidade;
     private String vmanTelefoneResidencial;
     private String vmanCelular;
     private String vmanNivel;
     private int vmanDivida;
     private String vmanAtivo;
     

    public VmanClientes() {
    }

	
    public VmanClientes(int vmanIdClientes) {
        this.vmanIdClientes = vmanIdClientes;
    }
    public VmanClientes(int vmanIdClientes, String vmanNome, String vmanCpf, String vmanRg, String vmanSexo, Date vmanDataNascimento, String vmanEmail, String vmanCep, String vmanendereço, String vmanBairro, String vmanCidade, String vmanTelefoneResidencial, String vmanCelular, String vmanNivel, int vmanDivida, String vmanAtivo) {
       this.vmanIdClientes = vmanIdClientes;
       this.vmanNome = vmanNome;
       this.vmanCpf = vmanCpf;
       this.vmanRg = vmanRg;
       this.vmanSexo = vmanSexo;
       this.vmanDataNascimento = vmanDataNascimento;
       this.vmanEmail = vmanEmail;
       this.vmanCep = vmanCep;
       this.vmanendereço = vmanendereço;
       this.vmanBairro = vmanBairro;
       this.vmanCidade = vmanCidade;
       this.vmanTelefoneResidencial = vmanTelefoneResidencial;
       this.vmanCelular = vmanCelular;
       this.vmanNivel = vmanNivel;
       this.vmanDivida = vmanDivida;
       this.vmanAtivo = vmanAtivo;
     
    }
   
     @Id 

    
    @Column(name="vman_idClientes", unique=true, nullable=false)
    public int getVmanIdClientes() {
        return this.vmanIdClientes;
    }
    
    public void setVmanIdClientes(int vmanIdClientes) {
        this.vmanIdClientes = vmanIdClientes;
    }

    
    @Column(name="vman_nome", length=100)
    public String getVmanNome() {
        return this.vmanNome;
    }
    
    public void setVmanNome(String vmanNome) {
        this.vmanNome = vmanNome;
    }

    
    @Column(name="vman_cpf", length=14)
    public String getVmanCpf() {
        return this.vmanCpf;
    }
    
    public void setVmanCpf(String vmanCpf) {
        this.vmanCpf = vmanCpf;
    }

    
    @Column(name="vman_rg", length=10)
    public String getVmanRg() {
        return this.vmanRg;
    }
    
    public void setVmanRg(String vmanRg) {
        this.vmanRg = vmanRg;
    }

    
    @Column(name="vman_sexo", length=1)
    public String getVmanSexo() {
        return this.vmanSexo;
    }
    
    public void setVmanSexo(String vmanSexo) {
        this.vmanSexo = vmanSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vman_dataNascimento", length=10)
    public Date getVmanDataNascimento() {
        return this.vmanDataNascimento;
    }
    
    public void setVmanDataNascimento(Date vmanDataNascimento) {
        this.vmanDataNascimento = vmanDataNascimento;
    }

    
    @Column(name="vman_email", length=80)
    public String getVmanEmail() {
        return this.vmanEmail;
    }
    
    public void setVmanEmail(String vmanEmail) {
        this.vmanEmail = vmanEmail;
    }

    
    @Column(name="vman_cep", length=9)
    public String getVmanCep() {
        return this.vmanCep;
    }
    
    public void setVmanCep(String vmanCep) {
        this.vmanCep = vmanCep;
    }

    
    @Column(name="vman_endereço", length=50)
    public String getVmanendereço() {
        return this.vmanendereço;
    }
    
    public void setVmanendereço(String vmanendereço) {
        this.vmanendereço = vmanendereço;
    }

    
    @Column(name="vman_bairro", length=30)
    public String getVmanBairro() {
        return this.vmanBairro;
    }
    
    public void setVmanBairro(String vmanBairro) {
        this.vmanBairro = vmanBairro;
    }

    
    @Column(name="vman_cidade", length=50)
    public String getVmanCidade() {
        return this.vmanCidade;
    }
    
    public void setVmanCidade(String vmanCidade) {
        this.vmanCidade = vmanCidade;
    }

    
    @Column(name="vman_telefoneResidencial", length=10)
    public String getVmanTelefoneResidencial() {
        return this.vmanTelefoneResidencial;
    }
    
    public void setVmanTelefoneResidencial(String vmanTelefoneResidencial) {
        this.vmanTelefoneResidencial = vmanTelefoneResidencial;
    }

    
    @Column(name="vman_celular", length=10)
    public String getVmanCelular() {
        return this.vmanCelular;
    }
    
    public void setVmanCelular(String vmanCelular) {
        this.vmanCelular = vmanCelular;
    }

    
    @Column(name="vman_nivel", length=30)
    public String getVmanNivel() {
        return this.vmanNivel;
    }
    
    public void setVmanNivel(String vmanNivel) {
        this.vmanNivel = vmanNivel;
    }

    
    @Column(name="vman_divida")
    public int getVmanDivida() {
        return this.vmanDivida;
    }
    
    public void setVmanDivida(int vmanDivida) {
        this.vmanDivida = vmanDivida;
    }

    
    @Column(name="vman_ativo", length=1)
    public String getVmanAtivo() {
        return this.vmanAtivo;
    }
    
    public void setVmanAtivo(String vmanAtivo) {
        this.vmanAtivo = vmanAtivo;
    }

    @Override
    public String toString() {
        return this.vmanIdClientes + " - " + this.vmanNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof VmanClientes) {
            VmanClientes vmanClientes = (VmanClientes) object;
            if (vmanClientes.getVmanIdClientes()== this.getVmanIdClientes()) {
                return true;
            }
        }
        return false;
    }



}


