package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmanVendedor generated by hbm2java
 */
@Entity
@Table(name="vman_vendedor"
    ,catalog="db_vinicius_nunes"
)
public class VmanVendedor  implements java.io.Serializable {


     private int vmanIdVendedor;
     private String vmanNome;
     private String vmanCpf;
     private String vmanSexo;
     private Date vmanDataNascimento;
     private String vmanEmail;
     private String vmanCep;
     private String vmanendereço;
     private String vmanBairro;
     private String vmanCidade;
     private String vmanCelular;
     private String vmanAtivo;
    

    public VmanVendedor() {
    }

	
    public VmanVendedor(int vmanIdVendedor) {
        this.vmanIdVendedor = vmanIdVendedor;
    }
    public VmanVendedor(int vmanIdVendedor, String vmanNome, String vmanCpf, String vmanSexo, Date vmanDataNascimento, String vmanEmail, String vmanCep, String vmanendereço, String vmanBairro, String vmanCidade, String vmanCelular, String vmanAtivo, Set vmanVendases) {
       this.vmanIdVendedor = vmanIdVendedor;
       this.vmanNome = vmanNome;
       this.vmanCpf = vmanCpf;
       this.vmanSexo = vmanSexo;
       this.vmanDataNascimento = vmanDataNascimento;
       this.vmanEmail = vmanEmail;
       this.vmanCep = vmanCep;
       this.vmanendereço = vmanendereço;
       this.vmanBairro = vmanBairro;
       this.vmanCidade = vmanCidade;
       this.vmanCelular = vmanCelular;
       this.vmanAtivo = vmanAtivo;
     
    }
   
     @Id 

    
    @Column(name="vman_idVendedor", unique=true, nullable=false)
    public int getVmanIdVendedor() {
        return this.vmanIdVendedor;
    }
    
    public void setVmanIdVendedor(int vmanIdVendedor) {
        this.vmanIdVendedor = vmanIdVendedor;
    }

    
    @Column(name="vman_nome", length=100)
    public String getVmanNome() {
        return this.vmanNome;
    }
    
    public void setVmanNome(String vmanNome) {
        this.vmanNome = vmanNome;
    }

    
    @Column(name="vman_cpf", length=14)
    public String getVmanCpf() {
        return this.vmanCpf;
    }
    
    public void setVmanCpf(String vmanCpf) {
        this.vmanCpf = vmanCpf;
    }

    
    @Column(name="vman_sexo", length=1)
    public String getVmanSexo() {
        return this.vmanSexo;
    }
    
    public void setVmanSexo(String vmanSexo) {
        this.vmanSexo = vmanSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vman_dataNascimento", length=10)
    public Date getVmanDataNascimento() {
        return this.vmanDataNascimento;
    }
    
    public void setVmanDataNascimento(Date vmanDataNascimento) {
        this.vmanDataNascimento = vmanDataNascimento;
    }

    
    @Column(name="vman_email", length=80)
    public String getVmanEmail() {
        return this.vmanEmail;
    }
    
    public void setVmanEmail(String vmanEmail) {
        this.vmanEmail = vmanEmail;
    }

    
    @Column(name="vman_cep", length=9)
    public String getVmanCep() {
        return this.vmanCep;
    }
    
    public void setVmanCep(String vmanCep) {
        this.vmanCep = vmanCep;
    }

    
    @Column(name="vman_endereço", length=50)
    public String getVmanendereço() {
        return this.vmanendereço;
    }
    
    public void setVmanendereço(String vmanendereço) {
        this.vmanendereço = vmanendereço;
    }

    
    @Column(name="vman_bairro", length=30)
    public String getVmanBairro() {
        return this.vmanBairro;
    }
    
    public void setVmanBairro(String vmanBairro) {
        this.vmanBairro = vmanBairro;
    }

    
    @Column(name="vman_cidade", length=50)
    public String getVmanCidade() {
        return this.vmanCidade;
    }
    
    public void setVmanCidade(String vmanCidade) {
        this.vmanCidade = vmanCidade;
    }

    
    @Column(name="vman_celular", length=10)
    public String getVmanCelular() {
        return this.vmanCelular;
    }
    
    public void setVmanCelular(String vmanCelular) {
        this.vmanCelular = vmanCelular;
    }

    
    @Column(name="vman_ativo", length=1)
    public String getVmanAtivo() {
        return this.vmanAtivo;
    }
    
    public void setVmanAtivo(String vmanAtivo) {
        this.vmanAtivo = vmanAtivo;
    }

   @Override
    public String toString() {
        return this.vmanIdVendedor + " - " + this.vmanNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof VmanVendedor) {
            VmanVendedor vmanVendore = (VmanVendedor) object;
            if (vmanVendore.getVmanIdVendedor()== this.getVmanIdVendedor()) {
                return true;
            }
        }
        return false;
    }




}


